### ISSUE TITLE
React 0.14 compatibilty

### ISSUE THREAD

**Issue by tamagokun** [stomita/react-lightning-design-system#1]
Wondering if there are any plans to do this, or if you'd like some help? I'm using a lot of these components for a project right now and am getting warning all over the place.

**Comment by andyengle** [comment]
I was also seeing such warnings and would be interested in an update.  I might be able to help here and there with doing some updates.

**Comment by andyengle** [comment]
https://github.com/stomita/react-lightning-design-system/pull/3

**Comment by stomita** [comment]
Thanks, @andyengle . I've merged the PR.
