### ISSUE TITLE
Cannot resolve module 'babel-runtime/helpers...' in version 0.2.2

### ISSUE THREAD

**Issue by rjmah** [stomita/react-lightning-design-system#16]
I'm trying to upgrade from version 0.1.22 to 0.2.2, but I'm running into issues when trying to build with webpack.

When I install v0.1.22, the following dependencies installed:
```
react-lightning-design-system@0.1.22 node_modules/react-lightning-design-system
├── svg4everybody@2.0.1
├── moment@2.11.0
└── babel-runtime@5.8.34 (core-js@1.2.6)
```

However, when I install v0.2.2, I am missing the babel-runtime dependency:
```
react-lightning-design-system@0.2.2 node_modules/react-lightning-design-system
├── svg4everybody@2.0.1
└── moment@2.11.0
```

I believe the fix for v0.2 would be to move babel-runtime from devDependencies to dependencies.

**Comment by ButuzGOL** [comment]
Please check https://github.com/stomita/react-lightning-design-system/pull/15 it might help

**Comment by ButuzGOL** [comment]
When pull be merged I will check

**Comment by eyaleizenberg** [comment]
@ButuzGOL I tried using your fork with the branch "webpack" but I can't npm start. I am hit with:
Cannot resolve module 'react-lightning-design-system'

**Comment by eyaleizenberg** [comment]
@stomita I am getting the same issue when trying it with your 0.1 branch

Any help?

**Comment by stomita** [comment]
Actually babel-runtime should be included in dependencies as it is a runtime lib. I'll fix it.

**Comment by eyaleizenberg** [comment]
@stomita Is there a quick fix I can do in the meantime until you deploy a fix?

**Comment by stomita** [comment]
@eyaleizenberg move "babel-runtime" in devDependencies to dependencies and run `npm install`

**Comment by stomita** [comment]
0.2.4 will fix the issue.

**Comment by eyaleizenberg** [comment]
@stomita 0.2.4 still doesn't work for me. 
`Module not found: Error: Cannot resolve module 'react-lightning-design-system'`

**Comment by stomita** [comment]
@eyaleizenberg Are you meaning you cannot run the examples in the repo ? If so, you should run `npm install` in "examples" folder before startup.

**Comment by eyaleizenberg** [comment]
@stomita no, I added this to my package.json
`"react-lightning-design-system": "github:stomita/react-lightning-design-system#e870f81"`

And when I require it in my component:
Lightning = require('react-lightning-design-system')

I get in my `npm start` terminal:
`Module not found: Error: Cannot resolve module 'react-lightning-design-system'`

**Comment by stomita** [comment]
@eyaleizenberg It is because you are using github reference in dependency. The source does not contain the transpiled code. Use official npm or clone the source code and build by your own.
