### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by ButuzGOL** [stomita/react-lightning-design-system#23]
What do you think ?
https://github.com/salesforce-ux/design-system/issues/147

**Comment by ButuzGOL** [comment]
May be suggestion of merging ?

**Comment by stomita** [comment]
I know they are using React actively (see the page of lightningdesignsystem.com with React devtools). I cannot say any also if the official doesn't disclose anything. As far as I can tell, this project is coming from a real project and our company product is utilizing these modules.
