### ISSUE TITLE
Modal #3 code doesn't match example

### ISSUE THREAD

**Issue by eyaleizenberg** [stomita/react-lightning-design-system#25]
So I am facing 2 issues:
1. I am trying to run the examples project and when I do `npm install` I am hit with:

  ```
  Invalid name: "@salesforce-ux/design-tokens"
  ```

2. I've written my component to match exactly your example of Modal #3 and I am getting different results. The HTML structure itself is different. Has the code changed since the examples were made?

Thanks.

**Comment by stomita** [comment]
Might be your npm is old. Check if you are using npm version 2 by `npm --version`.

**Comment by eyaleizenberg** [comment]
I'm on 3.3.6

**Comment by stomita** [comment]
Even in npm v3 I confirmed it can build. Please cleanup all packages in node_modules and re-run the `npm install`.
