### ISSUE TITLE
Close Modal on backdrop click

### ISSUE THREAD

**Issue by hossein-** [stomita/react-lightning-design-system#43]
Hi , First of all thanks for this great package and sorry for my bad English,

can you tell me how i can implement closing modal on backdrop click ? i think modals must have this feature, thanks again.

**Comment by hossein-** [comment]
Any update on this? i added onclick to [this line]("https://github.com/stomita/react-lightning-design-system/blob/master/src/scripts/Modal.js#L37") to hide the modal on backdrop click but it's not work,

`<div className={ backdropClassNames } onClick={this.hide.bind(this)}/>`

Any other idea ? thanks in advance.

**Comment by stomita** [comment]
You can create Pull Request to support the feature. I think it can be done by adding `onBackdropClick` and handle the `open` property of the modal.

**Comment by stomita** [comment]
If you wish a feature, you can create it by your own. If you want someone to help its creation, it might be possible, but only when anyone else really needs the feature.

**Comment by hossein-** [comment]
Yeah, just wondered why this isn't the default feature as all modals need to be closed by backdrop click,  anyway thanks for the tip mate
