### ISSUE TITLE
Lookup: Remove Selected Pill then Focus on Input

### ISSUE THREAD

**Issue by banderson5144** [stomita/react-lightning-design-system#51]
I have a question. Was the only way you were able to remove the selected pill and then re-focus to the ```<input>``` via the ```setTimeout()``` function? https://github.com/stomita/react-lightning-design-system/blob/master/src/scripts/Lookup.js#L329-333

**Comment by stomita** [comment]
The code you specified is to support *uncontrolled* behavior - which is managed by inner state and the props are given by `defaultSelected` or `defautlSearchText`. If you wish to control the behavior - that is *controlled* - you can set the `selected` and `searchText` props and manage the all behavior by the outer container.

In a *controlled* way, you can handle `onSelect` event and set the `selected` property to null. See `Lookup (controlled)` example in [LookupExamples.js](https://github.com/stomita/react-lightning-design-system/blob/master/examples/client/scripts/components/LookupExamples.js#L76-L85)
