### ISSUE TITLE
Ability to hard-code paths to icon files

### ISSUE THREAD

**Issue by john-benson** [stomita/react-lightning-design-system#54]
I need to be able to hard-code a variable path to the Icon's symbols paths. As it stands right now, there is a semi-defined route "<ASSET_ROOT>/icons/<CATEGORY>-sprite/svg/symbols.svg".

I will be issuing a PR that adds the ability to hard-code paths based on the category of the symbols. If the category has not been set, then it would default to the above path.

If this is something you'd prefer to not support, please feel free to reject the PR. If there are changes you need me to make, let me know and I'll update the code ASAP.

**Comment by john-benson** [comment]
I still working through exactly what I'll need.

I've closed my PR for now until I get things where I need them.

**Comment by stomita** [comment]
As I have no requirement of this PR presenting right now, I close this temporary.
