### ISSUE TITLE
Warning in React 15: unique "key" prop for FromElement 

### ISSUE THREAD

**Issue by john-benson** [stomita/react-lightning-design-system#57]
In FormElement, the control is built dynamically based on the props set; which includes adding a label and dropdown specific elements (if needed). This is then passed into renderFormElement as the "children" as an array, and rendered in place.

In React 15, this throws the following warning: 

> Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.

I have a temporary fix on my fork which simply relies on passing the "top" and "bottom" pieces individually and then rendering them individually. If you would like me to offer a PR of the change, please notify me and I will patch out those specific changes (along with some additional tests) into their own branch and offer a PR.

**Comment by raysmithdev** [comment]
Hey John,

Want me to take a look?

**Comment by john-benson** [comment]
@raysmithdev Thanks for the quick response. Let me carve out that PR for you right away.

**Comment by raysmithdev** [comment]
Sure, ping me. heading out but will take a look once back or in the morning

**Comment by john-benson** [comment]
@raysmithdev sounds good. no rush. My team has been working off my fork anyway we can continue to move forward with my changes for the time being. I know there is a better solution but I'm fairly unfamiliar with the entirety of the code base and it appears that FormElement is a core-component for many other pieces.

**Comment by john-benson** [comment]
@raysmithdev PR is up. if you have any recommendations or required changes let me know. I have some time to make updates as needed.

**Comment by raysmithdev** [comment]
I will fork and take a look tommorow no worries man :)

**Comment by raysmithdev** [comment]
Hey @john-benson,

I have forked code and running locally. So where am I looking for the issue exactly?

**Comment by john-benson** [comment]
@raysmithdev 

So the issue will occur for any code that uses the FormComponent. The easiest way to reproduce is do the following:

0. Checkount stomita/react-lightning-design-system#master
1. Bump react, react-dom and react-addons-test-utils to ^15.0.1
2. Bump enzyme to ^2.2.0
3. Add the following lines to your karma.conf.js (so that enzyme can run code for React 15)

```
karma.conf.js, starting at line 42

configure: function (bundle) {
   bundle.exclude('react/lib/ReactContext');
   bundle.exclude('react/lib/ExecutionEnvironment');
   bundle.exclude('jsdom');
   // new additions below
   bundle.external('react/addons');
   bundle.external('react/lib/ReactContext');
   bundle.external('react/lib/ExecutionEnvironment');
},
```

4. npm install
5. npm run test

You'll notice the warning near the top of your test output.

**Comment by ButuzGOL** [comment]
take a look to #60 I just add keys

**Comment by david-a** [comment]
here's a smalled PR just adding keys - https://github.com/stomita/react-lightning-design-system/pull/73

**Comment by ButuzGOL** [comment]
pr was merged
