### ISSUE TITLE
(React 15 issue?) Passing an undefined value to DateInput results in "`value` prop on `input` should not be null"

### ISSUE THREAD

**Issue by john-benson** [stomita/react-lightning-design-system#59]
Steps to reproduce:

1. Create a <DateInput /> without passing a value property; or by passing an undefined value.
2. Render the page.

Expected result:
An uncontrolled, empty DateInput is rendered without warnings or errors

Actual result:
An uncontrolled, empty DateInput is rendered, but the following error is shown in the console:

> warning.js:44 Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

I haven't checked if this is a React 15 specific issue but when I get a chance I will verify.

**Comment by john-benson** [comment]
After doing a bit of digging, it looks like this is the problem line:

```
src/scripts/DateInput.js; line 192

const inputValue =
      typeof this.state.inputValue !== 'undefined' ? this.state.inputValue :
      typeof dateValue !== 'undefined' && mvalue.isValid() ? mvalue.format(dateFormat) :
      null;
```

The defaulting to null if this.state.inputValue is null makes it impossible to have an "uncontrolled" DateInput.

**Comment by ButuzGOL** [comment]
pull request #60

**Comment by stomita** [comment]
Found it is resolved in the latest.
