### ISSUE TITLE
Add more people to the team

### ISSUE THREAD

**Issue by zokito** [stomita/react-lightning-design-system#67]
@stomita what would you say to a suggestion to add @ButuzGOL or maybe another trusted active contributor to the team so they could perform merges while you're away?
(not me I'm still a JS/React newbie)

**Comment by ButuzGOL** [comment]
I am ok with it

**Comment by stomita** [comment]
@ButuzGOL Thanks, I'm welcome, too. However the merging policy is not fully shared with the members yet. The best is to send PR to discuss within members before merging them into master (currently it is not always done in my commits). Do you have any preference of the collaboration ?

**Comment by ButuzGOL** [comment]
As I understand @zokito suggest to add me or somebody else to react-lightning-design-system/settings/collaboration so they will be able to merge pull requests
I think it would be good rule 
do merge if you don't response for long time (2 days for example) and person who do merge sure about pr anyway you can revert pr anytime

**Comment by stomita** [comment]
I've added @ButuzGOL to collaborators. I've also changed the master branch policy not to directly be pushed to make PR the primary way to update the master code.

**Comment by ButuzGOL** [comment]
Thanks @stomita I will try to check pr while you not available but I want to notice that I also spending much time on my private project

**Comment by nudelx** [comment]
Guys can you please review/check PRs made by me and @david-a , we are working on the same project based on react-lightning-design-system, following this have to push some add-ons and modifications onto. Sorry for bothering you but we have very tight deadlines. 
@zokito @stomita  => Maybe this is a good reason to add one of us to be a collaborator.
Thank you

**Comment by stomita** [comment]
@ButuzGOL @nudelx Year, we have many private projects. I have also, too. The contribution is not the  obligation and it is enough to contribute when you think it is valuable for you.

@nudelx If you have deadline in your local project, the merging is not always required - you can just use the forked version of it.
